@SmartSchool.Api_HostAddress = https://localhost:7144

GET {{SmartSchool.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SmartSchool.Api_HostAddress}}/api/student/Students/List

###

@id=1
GET {{SmartSchool.Api_HostAddress}}/api/student/Students/{{id}}

###

DELETE {{SmartSchool.Api_HostAddress}}/api/Student/{{id}}


###
